name             'drupal_box_wrapper'
maintainer       'E Source Companies, LLC'
maintainer_email 'dev@esource.com'
license          ''
description      'Wraps the cookbooks necessary for servering a Drupal site on Nginx, PHP-FPM, & MariaDB.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'firewalld'
depends 'mariadb'
depends 'memcached'
depends 'nginx'
depends 'nodejs'
depends 'npm'
depends 'ntp'
depends 'php-fpm'
depends 'rvm'
depends 'solr'
depends 'varnish'